"""add vital_readings table

Revision ID: 7c72b30a9bd4
Revises: eb080cf15419
Create Date: 2026-07-28 14:37:20.119064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c72b30a9bd4'
down_revision: Union[str, Sequence[str], None] = 'eb080cf15419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vital_type', sa.Enum('HEART_RATE', 'BP_SYSTOLIC', 'BP_DIASTOLIC', 'TEMPERATURE', 'BLOOD_OXYGEN', name='vitaltype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_readings_recorded_at'), 'vital_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_vital_readings_user_id'), 'vital_readings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vital_readings_user_id'), table_name='vital_readings')
    op.drop_index(op.f('ix_vital_readings_recorded_at'), table_name='vital_readings')
    op.drop_table('vital_readings')
    # ### end Alembic commands ###
