"""add health_profiles and allergies tables

Revision ID: 8374a866d00c
Revises: a7a0b2306c1f
Create Date: 2026-07-28 21:16:05.683583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8374a866d00c'
down_revision: Union[str, Sequence[str], None] = 'a7a0b2306c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_user_id'), 'allergies', ['user_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('alcohol', sa.Boolean(), nullable=False),
    sa.Column('exercise_frequency', sa.Enum('NEVER', 'SOMETIMES', 'MOSTLY', name='exercisefrequency'), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_allergies_user_id'), table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###
