"""add health_alerts table

Revision ID: add788e9c59c
Revises: 5c9c35d4c1bb
Create Date: 2026-07-29 02:49:24.024278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add788e9c59c'
down_revision: Union[str, Sequence[str], None] = '5c9c35d4c1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vital_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('WATCH', 'URGENT', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACKNOWLEDGED', 'ESCALATED', name='alertstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('latest_value', sa.String(), nullable=True),
    sa.Column('baseline_avg', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_alerts_user_id'), 'health_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_alerts_user_id'), table_name='health_alerts')
    op.drop_table('health_alerts')
    # ### end Alembic commands ###
