"""add care circle activity table

Revision ID: eb080cf15419
Revises: 3150572c12b1
Create Date: 2026-07-28 03:40:05.070171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb080cf15419'
down_revision: Union[str, Sequence[str], None] = '3150572c12b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_circle_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('care_circle_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('CONTACT_ADDED', 'CONTACT_REJECTED', 'URGENT_ALERT', 'CHECK_IN', name='activity_type_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['care_circle_id'], ['care_circles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('care_circle_activities')
    # ### end Alembic commands ###
