"""add user_vital_settings table

Revision ID: fb232a3d7fec
Revises: 7c72b30a9bd4
Create Date: 2026-07-28 19:36:52.404489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb232a3d7fec'
down_revision: Union[str, Sequence[str], None] = '7c72b30a9bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vital_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled_vitals', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vital_settings')
    # ### end Alembic commands ###
