// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF3-GOCtf9_lONY_JaEOZwy3ZqSxSQLI8',
    appId: '1:975976200606:web:bc8be3678a2f37ab0dbe8f',
    messagingSenderId: '975976200606',
    projectId: 'vitanet-62e40',
    authDomain: 'vitanet-62e40.firebaseapp.com',
    storageBucket: 'vitanet-62e40.firebasestorage.app',
    measurementId: 'G-2H994QGF7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ_XjO99ci23xoOy_1zfGZx3QGDH1ctvM',
    appId: '1:975976200606:android:41bd4b3e04251b760dbe8f',
    messagingSenderId: '975976200606',
    projectId: 'vitanet-62e40',
    storageBucket: 'vitanet-62e40.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQ0Abf4vnnXbFRGABnf_zf5L3PQyPT6w',
    appId: '1:975976200606:ios:92761ab4c0ba13b90dbe8f',
    messagingSenderId: '975976200606',
    projectId: 'vitanet-62e40',
    storageBucket: 'vitanet-62e40.firebasestorage.app',
    iosBundleId: 'com.vitanet.vitanet',
  );
}
